-- Usando uma CTE, liste os produtos que foram vendidos em 2012 junto com a quantidade total vendida e a categoria do produto.

-- COM CTE
WITH VALOR_VENDIDO AS (
    SELECT
        SOD.PRODUCTID AS ID,
        SUM(SOD.LINETOTAL) AS TOTAL_VENDIDO,
        YEAR(SSOH.ORDERDATE) AS ANO
    FROM SALES.SALESORDERDETAIL SOD
    INNER JOIN SALES.SALESORDERHEADER SSOH ON SSOH.SALESORDERID = SOD.SALESORDERID
    WHERE CAST(SSOH.ORDERDATE AS DATE) BETWEEN '2012-01-01' AND '2012-12-31'
    GROUP BY
        SOD.PRODUCTID,
        YEAR(SSOH.ORDERDATE))
SELECT
	VV.ID,
	PP.NAME AS PRODUTO,
	PPC.PRODUCTCATEGORYID AS CATEGORIA,
	VV.TOTAL_VENDIDO,
	VV.ANO
FROM VALOR_VENDIDO VV
	INNER JOIN PRODUCTION.PRODUCT PP ON PP.PRODUCTID = VV.ID
	INNER JOIN PRODUCTION.PRODUCTSUBCATEGORY PPSC ON PP.PRODUCTSUBCATEGORYID = PPSC.PRODUCTSUBCATEGORYID
	INNER JOIN PRODUCTION.PRODUCTCATEGORY PPC ON PPC.PRODUCTCATEGORYID = PPSC.PRODUCTCATEGORYID;

    -- SEM CTE
SELECT
	SOD.PRODUCTID AS ID,
	PP.NAME AS PRODUTO,
	PPC.PRODUCTCATEGORYID AS CATEGORIA,
	SUM(SOD.LINETOTAL) AS TOTAL_VENDIDO,
	YEAR(SSOH.ORDERDATE)
FROM SALES.SALESORDERDETAIL SOD
	INNER JOIN PRODUCTION.PRODUCT PP ON PP.PRODUCTID = SOD.PRODUCTID
	INNER JOIN PRODUCTION.PRODUCTSUBCATEGORY PPSC ON PP.PRODUCTSUBCATEGORYID = PPSC.PRODUCTSUBCATEGORYID
	INNER JOIN PRODUCTION.PRODUCTCATEGORY PPC ON PPC.PRODUCTCATEGORYID = PPSC.PRODUCTCATEGORYID
	INNER JOIN SALES.SALESORDERHEADER SSOH ON SSOH.SALESORDERID = SOD.SALESORDERID
WHERE CAST(SSOH.ORDERDATE AS DATE) BETWEEN '2012-01-01' AND '2012-12-31'
GROUP BY
	YEAR(SSOH.ORDERDATE),
	PP.NAME,
	PPC.PRODUCTCATEGORYID,
	SOD.PRODUCTID
ORDER BY TOTAL_VENDIDO DESC;


