-- Mostre os nomes dos departamentos e seus gerentes (nome completo do funcionário).

SELECT
PP.BUSINESSENTITYID,
PP.FIRSTNAME,
PP.LASTNAME,
HD.DEPARTMENTID,
HD.NAME AS NOME_DEPARTAMENTO,
HE.JOBTITLE
FROM PERSON.PERSON PP
INNER JOIN HUMANRESOURCES.EMPLOYEE HE ON HE.BUSINESSENTITYID = PP.BUSINESSENTITYID
INNER JOIN HUMANRESOURCES.EMPLOYEEDEPARTMENTHISTORY HEDH ON HEDH.BUSINESSENTITYID = PP.BUSINESSENTITYID
INNER JOIN HUMANRESOURCES.DEPARTMENT HD ON HD.DEPARTMENTID = HEDH.DEPARTMENTID
WHERE OrganizationLevel = 1