-- Calcule o total de vendas (LineTotal) por ano e região.

SELECT
    ST.NAME,
    SUM(SOD.LINETOTAL) AS SOMA_TOTAL
FROM SALES.SALESORDERHEADER SOH
    INNER JOIN SALES.SALESTERRITORY ST ON ST.TERRITORYID = SOH.TERRITORYID
    INNER JOIN SALES.SALESORDERDETAIL SOD ON SOD.SALESORDERID = SOH.SALESORDERID
WHERE cast(OrderDate as date) BETWEEN '2012-01-01' AND '2012-12-31'
GROUP BY ST.NAME