-- Encontre os produtos que nunca foram vendidos, com nome e categoria.

SELECT 
	PP.PRODUCTID,	
	PP.Name AS NOME_PRODUTO,
	PP.PRODUCTNUMBER
FROM PRODUCTION.PRODUCT PP
	LEFT JOIN SALES.SALESORDERDETAIL SOD ON SOD.PRODUCTID = PP.PRODUCTID
WHERE SOD.PRODUCTID IS NULL;