-- Liste os vendedores e o total vendido por cada um em 2023, ordenando do maior para o menor.

SELECT
	PP.BUSINESSENTITYID AS ID,
	PP.FIRSTNAME AS NOME,
	SUM(SOH.TOTALDUE) AS TOTAL,
	YEAR(SOH.ORDERDATE) AS ANO
FROM PERSON.PERSON PP
	INNER JOIN SALES.SALESORDERHEADER SOH ON SOH.SALESPERSONID = PP.BUSINESSENTITYID
WHERE CAST(ORDERDATE AS DATE) BETWEEN '2012-01-01' AND '2012-12-31'
GROUP BY 
	YEAR(SOH.ORDERDATE),
	PP.BusinessEntityID,
	PP.FirstName
ORDER BY
	TOTAL DESC
